plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
}

base {
    archivesName = project.archives_base_name + '-' + project.minecraft_version
}

version = project.mod_version
group = project.maven_group

repositories {
    maven { url 'https://masa.dy.fi/maven/sakura-ryoko' }
    maven { url 'https://maven.fallenbreath.me/releases' }
    maven { url 'https://maven.terraformersmc.com/releases/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "fi.dy.masa.malilib:malilib-fabric-26.2:${project.malilib_version}"
    compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"

    // To support mp3 playback
    implementation("javazoom:jlayer:1.0.1")
    // MP3SPI, used to decode mp3 files
    implementation("com.googlecode.soundlibs:mp3spi:1.9.5.4")
    // Tritonus Share, provides audio processing services
    implementation("com.googlecode.soundlibs:tritonus-share:0.3.7.4")
    // JFlac Codec, used to decode flac files
    implementation("org.jflac:jflac-codec:1.5.2")
    // ZXing Core, used for QR code processing
    implementation("com.google.zxing:core:3.5.1")
    include("javazoom:jlayer:1.0.1")
    include("com.googlecode.soundlibs:mp3spi:1.9.5.4")
    include("com.googlecode.soundlibs:tritonus-share:0.3.7.4")
    include("org.jflac:jflac-codec:1.5.2")
    include("com.google.zxing:core:3.5.1")
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "malilib_version": malilib_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = "UTF-8"
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE")
}
